### ISSUE TITLE
TODO U_Pl_Pg development

### ISSUE THREAD

**Issue by xaviertort** [ipouplana/KratosPoroGiDInterface#17]
## Overview
This issue intends to create a TODO list of the tasks that must be made to implement the two-phase flow in porous media formulation (currently the U_P<sub>l</sub>_P<sub>g</sub>) implemented in [Kratos Multiphysics](https://github.com/KratosMultiphysics/Kratos/tree/poro/feature-two-phase-flow) The idea is to order them by priority (and thematically) and check them when done.

This TODO list is thought to be collaborative, not just writing down the tasks to implement but some ideas to check that the implementation is well done, i.e. validation tests.

## How to proceed?
Just to control which are the newest tasks, write a comment with new tasks, and then I (@xaviertort) will add them to the main issue comment. This way, there will be a control on when these tasks are added.

When any of the tasks are completed, make a comment specifying which task is completed and, after this, check the task in this description and write the date at the beginning. For example
- [x] [14/03/2024] Add McWhorter test [(Commit `b8ebb4c`)](https://github.com/KratosMultiphysics/Kratos/commit/b8ebb4c08a21c4d70e171f6534a69b99885a3aba)

This systematic way of controlling the job done will facilitate the task of source control and report writing.

## Topics
The tasks are divided into different topics.

### TODO
- [ ] Implement H<sub>gl</sub> and the second term of H<sub>gg</sub> matrices in `CalculateAndAddPermeabilityMatrix`
- [ ] Implement H<sub>gl</sub> and the second term of H<sub>gg</sub> matrices in `CalculateAndAddPermeabilityFlow`
- [ ] Implement the second term of f<sub>pl</sub> and the 2nd, 3rd, 4th and 5th term of f<sub>pg</sub> in `CalculateAndAddFluidBodyFlow`

### Possible developments
- [ ] Study the necessity of adding a method to update permeability
- [ ] Study the necessity of adding a method to update porosity

### Formulation checks
- [ ] Check if Cgg is well defined in `GetCompressibilityCoefficients`
- [ ] Check if the density is well defined in `UpdateDensity`

### Validation tests
- [ ] Run the [Liakopoulos](https://www.opengeosys.org/docs/benchmarks/th2m/ogs-jupyter-lab-h2m-2d-liakopoulos/) test and compare the solution with OGS. Notice that the solution can be check [with](https://www.opengeosys.org/docs/benchmarks/th2m/ogs-jupyter-lab-h2m-2d-liakopoulos/) and [without](https://www.opengeosys.org/docs/benchmarks/two-phase-flow/two-phase-flow-pp-liakopoulos/) considering the mechanical part

### Bugfix
- [x] [19/11/2024] Fix gas discharge condition [(Commit `6a01f8b`)](https://github.com/KratosMultiphysics/Kratos/commit/6a01f8bc027d612fe6817279b717493f7a0f88b7)

**Comment by ipouplana** [comment]
Thank you very much @xaviertort !

**Comment by xaviertort** [comment]
The discharge condition bug was found and solved.
It seemed like a memory error on my PC at CIMNE. @ipouplana tried it on his computer and I tried it on my laptop and the condition is working well, increasing the gas pressure while injecting gas.

Nevertheless, we found that the DOFs are not sorted as in the single-phase (first displacement and then pressures). We did some tests to check that everything inside the element was done correctly. Then, we also checked what happens when the information is given to the core functions, as we were afraid of having some issues.

Finally, everything worked well and the correct implementation and assemblage of the local and global matrix are ensured.

**Comment by ipouplana** [comment]
@xaviertort , now that I remember, you could add that we may need to also implement a method to update porosity and permeability…

**Comment by xaviertort** [comment]
> @xaviertort , now that I remember, you could add that we may need to also implement a method to update porosity and permeability…

I renamed the first section as the list is about tasks that we already know and I added a new section called "Possible developments" in which we can add tasks that must be studied and discussed first
